/**
 * Planned rides as the SQL that seeds `public.rail_rides`.
 *
 * A pure function from rows to text, like `dbseed/sql.ts`, and for the same
 * reason: the seed is generated so it cannot drift from what generated it, and
 * a test regenerates it from the committed export digest and compares it byte
 * for byte.
 *
 * Every row carries an id derived from its own contents, so the insert can end
 * `on conflict (id) do nothing` and the file is safe to run twice. Without it a
 * second `db push --include-seed` would double the ride log, which for a table
 * whose whole purpose is counting would be the worst kind of quiet wrong.
 */

import { createHash } from 'node:crypto';

import type { Ride } from './plan.ts';

/**
 * A v5-style UUID over a ride's own values. Not a real namespaced UUID — the
 * namespace is this string rather than a registered one — but it is stable,
 * collision-resistant enough for 1,436 rows, and reproducible from the data.
 */
function rideId(ride: Ride): string {
  const digest = createHash('sha1')
    .update(`rail_rides:${ride.lineId}:${ride.riddenOn}:${ride.fromDidok}:${ride.toDidok}`)
    .digest('hex');
  const variant = ((parseInt(digest.slice(16, 18), 16) & 0x3f) | 0x80).toString(16);

  return [
    digest.slice(0, 8),
    digest.slice(8, 12),
    `5${digest.slice(13, 16)}`,
    `${variant}${digest.slice(18, 20)}`,
    digest.slice(20, 32),
  ].join('-');
}

export interface SeedContext {
  /** SHA-256 of the `.ics` these rides came from. */
  digest: string;
  /** The day the export was taken, and the last day rides were kept for. */
  through: string;
  days: number;
  byLine: Map<string, number>;
}

function header({ digest, through, days, byLine }: SeedContext): string {
  const counts = [...byLine]
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .map(([line, rows]) => `--   ${String(rows).padStart(5)}  ${line}`);

  return `-- Every ride to the office, generated by \`pnpm rides:data\` from a calendar
-- export. Do not edit by hand: rerun the command, or change the row in Studio.
--
-- The calendar records which days I went to the office and where to, not which
-- train I took, and no timetable can answer that for a past date. So the lines
-- come from the commute table in \`rail/src/rides/commute.ts\`, as ratios I gave
-- from memory: which lines appear here is fact, how often each one appears is
-- my estimate, and which line any single date carries is an artefact of how the
-- estimate was spread over the days. Count on the totals, not on a row.
--
-- Source export: sha256 ${digest}
-- Days: ${days.toLocaleString('en-US')} office days through ${through}, out and back.
--
${counts.join('\n')}

insert into public.rail_rides (id, line_id, ridden_on, from_didok, to_didok) values`;
}

export function renderRides(rides: Ride[], context: SeedContext): string {
  const values = rides.map(ride => {
    const cells = [rideId(ride), ride.lineId, ride.riddenOn, ride.fromDidok, ride.toDidok];

    return `(${cells.map(cell => `'${cell}'`).join(', ')})`;
  });

  return `${header(context)}\n  ${values.join(',\n  ')}\non conflict (id) do nothing;\n`;
}
