/**
 * Turns the recon's query results into `RECON.md`.
 *
 * Pure, and the conclusions are computed here rather than written by hand: a
 * report that asserts "every funicular is `route_type` 1400" is worth nothing if
 * the sentence survives a feed where that stopped being true. Every claim below
 * is derived from the rows it is printed next to, so a rerun that finds
 * something different says something different.
 *
 * Nothing here reads the clock. The report identifies itself by the publication
 * it describes, so two runs over the same feed produce the same bytes and the
 * December diff shows feed changes rather than run timestamps.
 */

import { cell, table } from '../markdown.ts';
import type {
  AgencyRow,
  CategoryRow,
  CombinationRow,
  LiftRow,
  OperatorRow,
  SampleRow,
  VariantRow,
} from './queries.ts';
import type { MirrorProbe } from './mirror.ts';

export interface FeedIdentity {
  id: string;
  source: string;
  page: string;
  filename: string | null;
  issued: string | null;
  sha256: string;
  bytes: number;
  members: string[];
}

export interface OperatorProbe {
  needle: string;
  matches: OperatorRow[];
}

export interface Findings {
  feed: FeedIdentity;
  combinations: CombinationRow[];
  categories: CategoryRow[];
  samples: SampleRow[];
  agencies: AgencyRow[];
  funiculars: LiftRow[];
  mistyped: LiftRow[];
  variants: VariantRow[];
  exceptions: SampleRow[];
  operators: OperatorProbe[];
  mirror: MirrorProbe;
}

const GEOMETRY_DATASET = {
  name: 'Eisenbahn-Streckennetz (BAV / swisstopo)',
  layer: 'ch.bav.schienennetz',
  url: 'https://data.geo.admin.ch/browser/index.html#/collections/ch.bav.schienennetz',
};

function plural(count: number, one: string, many = `${one}s`): string {
  return `${count.toLocaleString('en-US')} ${count === 1 ? one : many}`;
}

function sum(values: number[]): number {
  return values.reduce((total, value) => total + value, 0);
}

function sampleTable(rows: SampleRow[]): string {
  return table(
    [
      'route_id',
      'type',
      'desc',
      'short_name',
      'long_name',
      'Operator',
      'A trip_short_name',
      'Headsigns',
      'Trips',
    ],
    rows.map(row => [
      `\`${row.route_id}\``,
      row.route_type,
      row.route_desc,
      row.route_short_name,
      row.route_long_name,
      row.agency_name,
      row.trip_short_name,
      row.headsigns,
      row.trips,
    ]),
  );
}

function heading(findings: Findings): string {
  const { feed } = findings;

  return [
    '# Recon — what the timetable feed actually contains',
    '',
    'Generated by `pnpm recon:data`. It answers the six questions in',
    '[#467](https://github.com/owieth/portfolio/issues/467) against one named',
    'publication, so that #468 onwards filter on a vocabulary that was read off the',
    'feed rather than guessed at.',
    '',
    table(
      ['Field', 'Value'],
      [
        ['Feed', `\`${feed.id}\``],
        ['Source', `[${feed.source}](${feed.page})`],
        ['Archive', feed.filename === null ? null : `\`${feed.filename}\``],
        ['Published', feed.issued === null ? null : feed.issued.slice(0, 10)],
        ['Size', `${(feed.bytes / 1_000_000).toFixed(1)} MB`],
        ['sha256', `\`${feed.sha256}\``],
      ],
    ),
  ].join('\n');
}

/**
 * The acceptance criterion that matters: a contradiction has to be written down,
 * not worked around. Each entry is conditional on the rows, so one that gets
 * fixed upstream disappears from the report instead of being maintained.
 */
function contradictions(findings: Findings): string[] {
  const found: string[] = [];
  const { feed, categories, agencies, mirror } = findings;

  if (!feed.members.includes('shapes.txt')) {
    const mirrorSays = mirror.ok
      ? mirror.entries.includes('shapes.txt')
        ? ' The geOps mirror does have one.'
        : ' The geOps mirror does not have one either.'
      : ' The geOps mirror could not be checked.';

    found.push(
      'The README says GTFS `shapes.txt` "is checked first; if it covers most' +
        ' lines, OSM becomes the fallback rather than the primary source".' +
        ` There is no \`shapes.txt\` in this feed.${mirrorSays}` +
        ' OpenStreetMap is the primary geometry source, not a fallback, and' +
        ' #479/#480 are on the critical path rather than optional.',
    );
  }

  const longNames = sum(agencies.map(agency => agency.long_name));

  if (longNames === 0) {
    found.push(
      '`route_long_name` is empty on every route in the feed, not merely sparse.' +
        ' Any step that planned to fall back to it — naming a line with no number' +
        ' (#475) above all — has nothing to fall back to.',
    );
  }

  const extra = categories.filter(row => row.route_desc === 'EXT');

  if (extra.length > 0) {
    const types = [...new Set(extra.map(row => row.route_type))].join(', ');

    found.push(
      'The README includes `route_type` 100–117 and separately excludes `EXT`' +
        ` special-event trains. Those overlap: \`EXT\` is \`route_type\` ${types},` +
        ` ${plural(sum(extra.map(row => row.routes)), 'route')}. The include rule has to be` +
        ' stated as a `route_desc` allowlist, or the exclusion never fires.',
    );
  }

  const foreign = categories.filter(row =>
    ['TER', 'RB', 'TGV', 'ICE', 'NJ', 'RJX'].includes(row.route_desc ?? ''),
  );

  if (foreign.length > 0) {
    const routes = sum(foreign.map(row => row.routes));

    found.push(
      `The feed carries ${plural(routes, 'route')} under foreign categories` +
        ` (${foreign.map(row => `\`${row.route_desc}\``).join(', ')}), most of which are` +
        ' French, German and Austrian services that touch Switzerland or do not' +
        ' enter it at all. The README\'s include list does not mention them, and' +
        ' "every Swiss train line" is not the same set as "every line in the feed".',
    );
  }

  const trains = sum(
    categories.filter(row => row.route_desc === 'ZUG').map(row => row.routes),
  );

  if (trains > 0) {
    found.push(
      `\`route_desc\` \`ZUG\` — literally "train" — appears on ${plural(trains, 'route')},` +
        ' which is a category that carries no category. It has to be handled by name.',
    );
  }

  return found;
}

function sectionCombinations(findings: Findings): string {
  const { combinations, categories } = findings;

  const byDesc = new Map<string, Set<string>>();

  for (const row of categories) {
    const key = row.route_desc ?? '';
    byDesc.set(key, (byDesc.get(key) ?? new Set()).add(row.route_type));
  }

  const ambiguous = [...byDesc.entries()].filter(([, types]) => types.size > 1);

  const answer =
    ambiguous.length === 0
      ? '**`route_desc` is the real category vocabulary.** Every code maps to exactly' +
        ' one `route_type`, and several `route_type`s split into codes that matter —' +
        ' 102 is IC, EC, ICE and RJX; 106 is R, RE, RB and TER; 109 is S and SN.' +
        ' Filtering on `route_type` alone cannot express the include list; filtering' +
        ' on `route_desc` can.'
      : `**\`route_desc\` is not a function of \`route_type\`.** ${ambiguous
          .map(([desc, types]) => `\`${desc}\` appears as ${[...types].join(' and ')}`)
          .join('; ')}. Both fields are needed to identify a category.`;

  return [
    '## 1. Route types, categories and operators',
    '',
    'Every `(route_type, route_desc)` in the feed, excluded codes included — the' +
      ' point is to see what is being thrown away.',
    '',
    table(
      ['route_type', 'route_desc', 'Routes', 'Trips', 'Agencies'],
      categories.map(row => [
        row.route_type,
        row.route_desc,
        row.routes,
        row.trips,
        row.agencies,
      ]),
    ),
    '',
    answer,
    '',
    `### The candidate set, per operator (${plural(combinations.length, 'combination')})`,
    '',
    'Distinct `(route_type, route_desc, agency_id)` across the routes the README' +
      ' proposes to include — `route_type` 100–199 plus 1400.',
    '',
    table(
      ['route_type', 'route_desc', 'agency_id', 'Operator', 'Routes', 'Trips'],
      combinations.map(row => [
        row.route_type,
        row.route_desc,
        row.agency_id,
        row.agency_name,
        row.routes,
        row.trips,
      ]),
    ),
  ].join('\n');
}

function sectionSamples(findings: Findings): string {
  const { samples, variants, exceptions } = findings;

  const candidates = sum(variants.map(row => row.routes));
  const categoryOnly = sum(variants.filter(row => row.category_only).map(row => row.routes));
  const share = ((categoryOnly / candidates) * 100).toFixed(0);

  const marked = variants.filter(row => row.y_variant);
  const leaks = sum(marked.filter(row => !row.category_only).map(row => row.routes));

  const rule =
    leaks > 0
      ? `**The marker is not reliable**: ${plural(leaks, 'route')} carries a \`-Y-\`` +
        ' variant and a real line number anyway, so the string test is the only test.'
      : '**The feed marks them.** A `route_id` whose variant segment is `Y` never' +
        ' carries a line number, without exception, and the second segment of such' +
        ' an id is a surrogate rather than a number — #474 must not read one out of it.' +
        (exceptions.length === 0
          ? ' The converse holds too, so either test may be used.'
          : ` The converse does not hold — ${plural(exceptions.length, 'route')} below` +
            ` ${exceptions.length === 1 ? 'is' : 'are'} category-only without the marker` +
            ' — so the string test is the one to filter on and the marker is' +
            ' corroboration.');

  const sections = [
    '## 2. Routes whose short name is only a category',
    '',
    `${plural(categoryOnly, 'route')} of ${candidates.toLocaleString('en-US')} in the` +
      ` candidate set — ${share}% — have a \`route_short_name\` that is nothing but the` +
      ' category. The twenty busiest, with every field that might carry a number' +
      ' instead:',
    '',
    sampleTable(samples),
    '',
    'Every one of them is empty in `route_long_name` and carries a different' +
      ' `trip_short_name` on every departure. These are the lines #475 has to name' +
      ' from operator, category and terminals.',
    '',
    '### Telling them apart without a string test',
    '',
    table(
      ['`route_id` variant is `Y`', 'Short name is only the category', 'Routes'],
      variants.map(row => [
        row.y_variant ? 'yes' : 'no',
        row.category_only ? 'yes' : 'no',
        row.routes,
      ]),
    ),
    '',
    rule,
  ];

  if (exceptions.length > 0) {
    sections.push(
      '',
      table(
        ['route_id', 'type', 'desc', 'short_name', 'Operator'],
        exceptions.map(row => [
          `\`${row.route_id}\``,
          row.route_type,
          row.route_desc,
          row.route_short_name,
          row.agency_name,
        ]),
      ),
    );
  }

  return sections.join('\n');
}

function sectionLineNumber(findings: Findings): string {
  const { agencies } = findings;

  const routes = sum(agencies.map(agency => agency.routes));
  const categoryOnly = sum(agencies.map(agency => agency.category_only));
  const longNames = sum(agencies.map(agency => agency.long_name));

  const weighted =
    sum(agencies.map(agency => agency.trip_short_name_per_route * agency.routes)) / routes;

  const clean = agencies.filter(agency => agency.category_only === 0).length;

  return [
    '## 3. Which field carries the passenger-facing line number',
    '',
    'Per operator, across the candidate set. `trip_short_name/route` is the average' +
      ' number of distinct `trip_short_name`s on one route: a line number would be 1.',
    '',
    table(
      [
        'agency_id',
        'Operator',
        'Routes',
        'Category-only',
        'long_name set',
        'Distinct short_names',
        'trip_short_name/route',
        'Trips',
      ],
      agencies.map(agency => [
        agency.agency_id,
        agency.agency_name,
        agency.routes,
        agency.category_only,
        agency.long_name,
        agency.distinct_short_names,
        agency.trip_short_name_per_route,
        agency.trips,
      ]),
    ),
    '',
    '**`route_short_name`, and there is no second candidate.**',
    '',
    `- \`route_long_name\` is set on ${longNames.toLocaleString('en-US')} of` +
      ` ${routes.toLocaleString('en-US')} routes. It is not a fallback; it is not populated.`,
    `- \`trip_short_name\` averages ${weighted.toFixed(0)} distinct values per route. It is` +
      ' the train number, exactly as the issue suspected — one per departure, useless' +
      ' as an identity.',
    `- \`route_short_name\` is populated on every route, but on ${categoryOnly.toLocaleString('en-US')}` +
      ' of them it holds the category and nothing else.' +
      ` ${clean.toLocaleString('en-US')} of ${agencies.length.toLocaleString('en-US')} operators` +
      ' number all of their routes; the rest number none or some.',
    '',
    'So the per-operator answer is not "a different field" but "the same field, or' +
      ' nothing". There is no operator that hides the line number elsewhere, which' +
      ' means #475 is unavoidable rather than a nicety.',
  ].join('\n');
}

function sectionGeometry(findings: Findings): string {
  const { feed, mirror } = findings;

  const official = feed.members.includes('shapes.txt');

  const mirrorLine = mirror.ok
    ? `- **geOps mirror** (\`${mirror.url}\`, ${(mirror.archiveBytes / 1_000_000).toFixed(0)} MB):` +
      ` ${mirror.entries.includes('shapes.txt') ? '**has** `shapes.txt`' : 'no `shapes.txt`'}.` +
      ` Members: ${mirror.entries.map(name => `\`${name}\``).join(', ')}.`
    : `- **geOps mirror** (\`${mirror.url}\`): could not be checked — ${mirror.reason}.`;

  return [
    '## 4. Is there a `shapes.txt`',
    '',
    `- **Official feed** (\`${feed.id}\`):` +
      ` ${official ? '**has** `shapes.txt`' : 'no `shapes.txt`'}.` +
      ` Members: ${feed.members.map(name => `\`${name}\``).join(', ')}.`,
    mirrorLine,
    `- **${GEOMETRY_DATASET.name}** (\`${GEOMETRY_DATASET.layer}\`): line geometry for the` +
      ' Swiss network exists and is public, but it is a geodata layer keyed on the BAV' +
      ' line number, not on anything in the GTFS feed. Joining it would mean first' +
      ' recovering a BAV line number per GTFS route, which the feed does not publish' +
      ` except incidentally on funiculars. [Dataset](${GEOMETRY_DATASET.url}).`,
    '',
    official
      ? '**The feed has geometry.** Check its coverage before committing to Overpass.'
      : '**Neither GTFS source ships geometry.** The README has this the wrong way round:' +
        ' OpenStreetMap is the only practical source of line shapes, so #479 and #480' +
        ' are the primary path and there is no GTFS fallback behind them. The BAV layer' +
        ' is a second-order option that costs a join the feed cannot currently support.',
  ].join('\n');
}

function sectionFuniculars(findings: Findings): string {
  const { funiculars, mistyped, categories } = findings;

  const typed = new Set(funiculars.map(row => row.route_type));
  const types = [...typed];
  const descs = [...new Set(funiculars.map(row => row.route_desc ?? '—'))];

  // Asked of the whole feed, not of the funicular rows: the interesting failure
  // is a FUN route typed as something else, which by definition is not in them.
  const strayDesc = categories.filter(
    row => row.route_desc === 'FUN' && !typed.has(row.route_type),
  );

  const agreement =
    types.length === 1 && descs.length === 1 && strayDesc.length === 0
      ? `\`route_type\` ${types[0]} and \`route_desc\` \`${descs[0]}\` select exactly the` +
        ' same set. Either test alone is enough, and neither contradicts the other.'
      : `The two tests disagree: \`route_type\` ${types.join('/')} against \`route_desc\`` +
        ` ${descs.map(desc => `\`${desc}\``).join('/')}` +
        (strayDesc.length === 0
          ? '.'
          : `, and \`FUN\` also appears as \`route_type\` ${strayDesc
              .map(row => row.route_type)
              .join(', ')}.`);

  const answer =
    mistyped.length === 0
      ? '**No aerial-lift route is run by a company that calls itself a funicular**, so' +
        ' nothing suggests a Standseilbahn is hiding in 1300. `route_type = 1400` is' +
        ' safe as the include rule and 1300 can be excluded wholesale.'
      : `**${plural(mistyped.length, 'route')} outside 1400 belong${
          mistyped.length === 1 ? 's' : ''
        } to an operator whose name says funicular**, listed at the end of this section.` +
        ' Each needs a look before #468 excludes 1300 wholesale — an operator that runs' +
        ' both a funicular and a chairlift will show up here without anything being' +
        ' mistyped.';

  const sections = [
    '## 5. Are all funiculars `route_type` 1400',
    '',
    `The feed has ${plural(funiculars.length, 'funicular route')}. ${agreement}`,
    '',
    answer,
    '',
    table(
      ['Operator', 'short_name', 'route_id', 'Trips'],
      funiculars.map(row => [
        row.agency_name,
        row.route_short_name,
        `\`${row.route_id}\``,
        row.trips,
      ]),
    ),
    '',
    'Note the short names: a funicular\'s `route_short_name` is a BAV line number' +
      ' (`2350`), a local code (`TG`), or the bare category — never something a' +
      ' passenger would say. #475 has to name all 53 of these from the operator.',
  ];

  if (mistyped.length > 0) {
    sections.push(
      '',
      '### Aerial-lift and bus routes run by a company that calls itself a funicular',
      '',
      table(
        ['route_type', 'route_desc', 'Operator', 'short_name', 'route_id'],
        mistyped.map(row => [
          row.route_type,
          row.route_desc,
          row.agency_name,
          row.route_short_name,
          `\`${row.route_id}\``,
        ]),
      ),
    );
  }

  return sections.join('\n');
}

function sectionOperators(findings: Findings): string {
  const { operators } = findings;

  const missing = operators.filter(probe => probe.matches.length === 0);

  return [
    '## 6. Do the privately run funiculars appear at all',
    '',
    'A company with no transport concession has no obligation to publish a' +
      ' timetable, so the named ones are worth checking individually rather than' +
      ' inferring from a count.',
    '',
    table(
      ['Searched for', 'Found as', 'agency_id', 'route_type', 'Routes'],
      operators.flatMap(probe =>
        probe.matches.length === 0
          ? [[probe.needle, '**absent**', null, null, 0]]
          : probe.matches.map(match => [
              probe.needle,
              match.agency_name,
              match.agency_id,
              match.route_types,
              match.routes,
            ]),
      ),
    ),
    '',
    missing.length === 0
      ? '**All of them are in the feed**, including the Polybahn, which is the one the' +
        ' issue singled out. No hand-written seed is needed for these; whether #476 is' +
        ' needed at all depends on a funicular nobody has thought to search for.'
      : `**${plural(missing.length, 'operator')} of the ones searched for ${
          missing.length === 1 ? 'is' : 'are'
        } absent** — ${missing
          .map(probe => probe.needle)
          .join(', ')}. That is what #476's seed file is for.`,
  ].join('\n');
}

export function render(findings: Findings): string {
  const found = contradictions(findings);

  const contradictionSection = [
    '## Contradictions with the brief',
    '',
    found.length === 0
      ? 'None. Every assumption in `README.md` that this recon could test held.'
      : found.map((entry, index) => `${index + 1}. ${entry}`).join('\n\n'),
  ].join('\n');

  return `${[
    heading(findings),
    contradictionSection,
    sectionCombinations(findings),
    sectionSamples(findings),
    sectionLineNumber(findings),
    sectionGeometry(findings),
    sectionFuniculars(findings),
    sectionOperators(findings),
  ].join('\n\n')}\n`;
}
