import type { Flight } from '@/lib/stats/flights/types';

/**
 * The seed, mirrored from `supabase/migrations/20260921061623_seed_flights.sql`
 * so the numbers asserted against it are the numbers the page renders. Ids
 * stand in for the generated uuids; nothing reads them.
 *
 * Shared rather than local to one suite: `stats.test.ts` derives every total
 * from it, and the registry tests assert that every `airline` and `aircraft`
 * value in it resolves. `.fixture.ts` rather than `.test.ts` so
 * `vitest.config.mts`'s `include` does not try to run it as an empty suite.
 *
 * Two shapes are load-bearing and must survive any edit: the open jaw (out to
 * Boston, back from New York) and the Vienna connection in both directions.
 * They are what break a naive "every flight is a return trip" assumption.
 */
export const SEED = [
  {
    id: '01',
    flownOn: '2017-07-14',
    origin: 'ZRH',
    destination: 'BCN',
    airline: 'LX',
    flightNumber: '1954',
    aircraft: 'A320',
    durationMinutes: 110,
  },
  {
    id: '02',
    flownOn: '2017-07-21',
    origin: 'BCN',
    destination: 'ZRH',
    airline: 'LX',
    flightNumber: '1955',
    aircraft: 'A320',
    durationMinutes: 105,
  },
  {
    id: '03',
    flownOn: '2018-03-09',
    origin: 'ZRH',
    destination: 'LHR',
    airline: 'LX',
    flightNumber: '338',
    aircraft: 'A220-300',
    durationMinutes: 110,
  },
  {
    id: '04',
    flownOn: '2018-03-12',
    origin: 'LHR',
    destination: 'ZRH',
    airline: 'LX',
    flightNumber: '339',
    aircraft: 'A220-300',
    durationMinutes: 100,
  },
  {
    id: '05',
    flownOn: '2018-09-28',
    origin: 'BSL',
    destination: 'AMS',
    airline: 'KL',
    flightNumber: '1982',
    aircraft: 'E190',
    durationMinutes: 90,
  },
  {
    id: '06',
    flownOn: '2018-10-02',
    origin: 'AMS',
    destination: 'BSL',
    airline: 'KL',
    flightNumber: '1983',
    aircraft: 'E190',
    durationMinutes: 85,
  },
  {
    id: '07',
    flownOn: '2019-05-17',
    origin: 'ZRH',
    destination: 'OSL',
    airline: 'LX',
    flightNumber: '1268',
    aircraft: 'A220-100',
    durationMinutes: 145,
  },
  {
    id: '08',
    flownOn: '2019-05-24',
    origin: 'OSL',
    destination: 'ZRH',
    airline: 'LX',
    flightNumber: '1269',
    aircraft: 'A220-100',
    durationMinutes: 140,
  },
  {
    id: '09',
    flownOn: '2019-11-01',
    origin: 'ZRH',
    destination: 'LIS',
    airline: 'LX',
    flightNumber: '2080',
    aircraft: 'A320neo',
    durationMinutes: 170,
  },
  {
    id: '10',
    flownOn: '2019-11-08',
    origin: 'LIS',
    destination: 'ZRH',
    airline: 'LX',
    flightNumber: '2081',
    aircraft: 'A320neo',
    durationMinutes: 160,
  },
  {
    id: '11',
    flownOn: '2021-08-13',
    origin: 'ZRH',
    destination: 'LHR',
    airline: 'BA',
    flightNumber: '711',
    aircraft: 'A320',
    durationMinutes: 105,
  },
  {
    id: '12',
    flownOn: '2021-08-16',
    origin: 'LHR',
    destination: 'ZRH',
    airline: 'BA',
    flightNumber: '716',
    aircraft: 'A320',
    durationMinutes: 95,
  },
  {
    id: '13',
    flownOn: '2022-04-22',
    origin: 'ZRH',
    destination: 'BER',
    airline: 'LX',
    flightNumber: '1082',
    aircraft: 'A220-300',
    durationMinutes: 85,
  },
  {
    id: '14',
    flownOn: '2022-04-25',
    origin: 'BER',
    destination: 'ZRH',
    airline: 'LX',
    flightNumber: '1083',
    aircraft: 'A220-300',
    durationMinutes: 90,
  },
  {
    id: '15',
    flownOn: '2022-09-30',
    origin: 'ZRH',
    destination: 'VIE',
    airline: 'OS',
    flightNumber: '566',
    aircraft: 'A320',
    durationMinutes: 80,
  },
  {
    id: '16',
    flownOn: '2022-09-30',
    origin: 'VIE',
    destination: 'RHO',
    airline: 'OS',
    flightNumber: '813',
    aircraft: 'A320',
    durationMinutes: 135,
  },
  {
    id: '17',
    flownOn: '2022-10-09',
    origin: 'RHO',
    destination: 'VIE',
    airline: 'OS',
    flightNumber: '814',
    aircraft: 'A320',
    durationMinutes: 140,
  },
  {
    id: '18',
    flownOn: '2022-10-09',
    origin: 'VIE',
    destination: 'ZRH',
    airline: 'OS',
    flightNumber: '561',
    aircraft: 'A320',
    durationMinutes: 85,
  },
  {
    id: '19',
    flownOn: '2023-06-02',
    origin: 'GVA',
    destination: 'LHR',
    airline: 'BA',
    flightNumber: '731',
    aircraft: 'A320neo',
    durationMinutes: 105,
  },
  {
    id: '20',
    flownOn: '2023-06-06',
    origin: 'LHR',
    destination: 'GVA',
    airline: 'BA',
    flightNumber: '730',
    aircraft: 'A320neo',
    durationMinutes: 95,
  },
  {
    id: '21',
    flownOn: '2024-02-16',
    origin: 'ZRH',
    destination: 'OSL',
    airline: 'SK',
    flightNumber: '1478',
    aircraft: 'A320neo',
    durationMinutes: 150,
  },
  {
    id: '22',
    flownOn: '2024-02-23',
    origin: 'OSL',
    destination: 'ZRH',
    airline: 'SK',
    flightNumber: '1477',
    aircraft: 'A320neo',
    durationMinutes: 145,
  },
  {
    id: '23',
    flownOn: '2025-03-07',
    origin: 'ZRH',
    destination: 'LHR',
    airline: 'LX',
    flightNumber: '316',
    aircraft: 'A220-300',
    durationMinutes: 110,
  },
  {
    id: '24',
    flownOn: '2025-03-11',
    origin: 'LHR',
    destination: 'ZRH',
    airline: 'LX',
    flightNumber: '317',
    aircraft: 'A220-300',
    durationMinutes: 100,
  },
  {
    id: '25',
    flownOn: '2026-05-08',
    origin: 'ZRH',
    destination: 'BOS',
    airline: 'LX',
    flightNumber: '54',
    aircraft: 'A330-300',
    durationMinutes: 505,
  },
  {
    id: '26',
    flownOn: '2026-05-19',
    origin: 'JFK',
    destination: 'ZRH',
    airline: 'LX',
    flightNumber: '17',
    aircraft: 'B777-300ER',
    durationMinutes: 460,
  },
] as const satisfies readonly Flight[];
