import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.scss'

const inter = Inter({ subsets: ['latin'] });

const footerItems = [];

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.description}>
          <h1 className={inter.className}>Hello. Hallo. Hola. Hej. Hoi.</h1>

          <h2 className={inter.className}>I'm Olivier</h2>
        </div>

        <div className={styles.footer}>
          <div>

          </div>
        </div>
      </main>
    </>
  )
}
