import Footer from '@/components/Footer';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Header from '@/components/Header';
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';

const soehne = localFont({
  src: '../../public/fonts/soehne-buch.woff2',
  weight: '400',
  style: 'normal',
});

export const metadata: Metadata = {
  title: 'Olivier Winkler',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const styles = {
    main: [
      'relative',
      'flex',
      'min-h-[85vh]',
      'flex-col',
      'items-center',
      'justify-center',
      'p-24',
    ].join(' '),
  };

  return (
    <html lang="en">
      <body className={`${GeistSans.variable} ${GeistMono.variable} font-sans`}>
        <Header />
        <main className={styles.main}>{children}</main>
        {/* <Dock /> */}
        <Footer />
      </body>
    </html>
  );
}
