import Footer from '@/components/Footer';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Header from '@/components/Header';

const aeonik = localFont({
  src: '../../public/fonts/Aeonik-Medium.woff2',
  weight: '400',
  style: 'normal',
});

const soehne = localFont({
  src: '../../public/fonts/soehne-buch.woff2',
  weight: '400',
  style: 'normal',
});

export const metadata: Metadata = {
  title: 'Olivier Winkler',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={aeonik.className}>
        <Header />
        {children}
        {/* <Dock /> */}
        <Footer />
      </body>
    </html>
  );
}
