/**
 * Turns what the build found into `REPORT.md`, the file read each December
 * before the snapshot is committed.
 *
 * Every step already sets aside what it could not settle on its own: routes the
 * allowlist did not recognise, stations the Swiss check doubted, lines the merge
 * suspects, names that were derived or written by hand, lines nothing in OSM
 * draws. This lists them, next to the counts that say whether the whole is the
 * right size, and decides nothing.
 *
 * Pure, and nothing here reads the clock. The report names the publication and
 * the OSM answers it was built from, so two runs over the same inputs write the
 * same bytes and the diff of `REPORT.md` shows what changed in the data.
 *
 * Each section is sized to be read by hand. The long one is the lines with no
 * geometry, so the ones that run for eight weeks or fewer — construction
 * replacements and one-off specials, which OSM does not map — are folded away
 * under their own count rather than mixed in with the misses worth chasing.
 */

import type { Tally as RouteTally } from '../allowlist.ts';
import { table } from '../markdown.ts';
import type { Cell } from '../markdown.ts';
import type { UnmatchedReason, Unmatched } from '../match.ts';
import type { Suspect } from '../merge.ts';
import { compare } from '../merge/key.ts';
import type { Misplaced, Station } from '../stations.ts';
import type { TerminiLine } from '../termini.ts';

/** Lines that run in this many weeks or fewer are folded away in the unmatched lists. */
export const SHORT_LIVED_WEEKS = 8;

const FUNICULAR = 'FUN';

export interface ReportFeed {
  id: string;
  source: string;
  page: string;
  filename: string | null;
  issued: string | null;
}

export interface ReportInput {
  feed: ReportFeed;
  /** The OSM timestamp of each Overpass answer, by route type. */
  osmBase: Readonly<Record<string, string>>;
  lines: readonly TerminiLine[];
  /** Region slug to display name, from `data/regions.json`. Operator slugs have none. */
  regionNames: Readonly<Record<string, string>>;
  /** For the names of a suspect part's terminals. */
  stations: readonly Station[];
  unmatched: readonly Unmatched[];
  suspect: readonly Suspect[];
  /** Seeded ids with a stop a feed line of the same category now serves. */
  inFeed: readonly string[];
  misplaced: readonly Misplaced[];
  /** Routes the allowlist recognised neither as included nor as excluded. */
  unknownRoutes: readonly RouteTally[];
}

const REASONS: readonly { reason: UnmatchedReason; says: string }[] = [
  { reason: 'no-candidate', says: 'no relation passed any rule' },
  {
    reason: 'low-coverage',
    says: 'relations passed, but reach too few of the line’s stations',
  },
  { reason: 'contested', says: 'its relations went to lines with a stronger claim' },
];

function count(value: number): string {
  return value.toLocaleString('en-US');
}

function plural(value: number, noun: string): string {
  return `${count(value)} ${value === 1 ? noun : `${noun}s`}`;
}

function code(value: string): string {
  return `\`${value}\``;
}

function percent(share: number): string {
  return `${Math.round(share * 100)}%`;
}

function isFunicular(line: TerminiLine): boolean {
  return line.category === FUNICULAR;
}

function isShortLived(line: TerminiLine | undefined): boolean {
  return (
    line?.serviceWeeks !== null &&
    line?.serviceWeeks !== undefined &&
    line.serviceWeeks <= SHORT_LIVED_WEEKS
  );
}

/** A table, or one line saying there is nothing to review. */
function listing(headers: string[], rows: Cell[][], none = '_None._'): string {
  return rows.length === 0 ? none : table(headers, rows);
}

function byId<T extends { id: string }>(items: readonly T[]): T[] {
  return [...items].sort((a, b) => compare(a.id, b.id));
}

function heading(input: ReportInput): string {
  const { feed, osmBase } = input;
  const osm = Object.keys(osmBase)
    .sort(compare)
    .map((routeType): Cell[] => [`OSM, ${routeType}`, osmBase[routeType]]);

  return [
    '# Rail lines — build report',
    '',
    'Generated by `pnpm build:data`, next to `lines.csv`, `line_stops.csv`,',
    '`lines.json` and `lines.geojson`. It lists everything the build could not',
    'settle on its own, so read it before committing the snapshot. These are the',
    'rows most likely to need a hand edit once the lines are seeded.',
    '',
    table(
      ['Field', 'Value'],
      [
        ['Feed', code(feed.id)],
        ['Source', `[${feed.source}](${feed.page})`],
        ['Archive', feed.filename === null ? null : code(feed.filename)],
        ['Published', feed.issued === null ? null : feed.issued.slice(0, 10)],
        ...osm,
      ],
    ),
  ].join('\n');
}

function sectionTotals(lines: readonly TerminiLine[]): string {
  const split = (subset: readonly TerminiLine[]): Cell[] => {
    const funiculars = subset.filter(isFunicular).length;

    return [subset.length - funiculars, funiculars, subset.length];
  };
  const trains = lines.filter(line => !isFunicular(line)).length;

  return [
    '## Totals',
    '',
    `**${plural(lines.length, 'line')}: ${plural(trains, 'train line')} and ${plural(lines.length - trains, 'funicular')}.**`,
    'A funicular is a line of category `FUN`. Everything else, rack railways',
    'included, is a train.',
    '',
    table(
      ['', 'Trains', 'Funiculars', 'Lines'],
      [
        ['From the feed', ...split(lines.filter(line => line.source === 'feed'))],
        ['Seeded by hand', ...split(lines.filter(line => line.source === 'manual'))],
        ['**All**', ...split(lines)],
      ],
    ),
  ].join('\n');
}

function sectionCategories(lines: readonly TerminiLine[]): string {
  const categories = new Map<string, TerminiLine[]>();

  for (const line of lines) {
    categories.set(line.category, [...(categories.get(line.category) ?? []), line]);
  }

  const rows = [...categories.entries()]
    .sort(([a, first], [b, second]) => second.length - first.length || compare(a, b))
    .map(([category, members]): Cell[] => [
      code(category),
      members.length,
      members.filter(line => line.hasGeometry).length,
      members.filter(line => line.seasonal === true).length,
    ]);

  return [
    '## By category',
    '',
    'Busiest first. Seasonal lines run in fewer than two thirds of the feed',
    'year’s weeks; a line seeded by hand is never counted as one.',
    '',
    table(['Category', 'Lines', 'With geometry', 'Seasonal'], rows),
  ].join('\n');
}

function sectionRegions(input: ReportInput): string {
  const regions = new Map<string, TerminiLine[]>();

  for (const line of input.lines) {
    regions.set(line.region, [...(regions.get(line.region) ?? []), line]);
  }

  const slugs = [...regions.keys()].sort(compare);
  const named = slugs.filter(slug => Object.hasOwn(input.regionNames, slug));
  const byOperator = slugs.filter(slug => !Object.hasOwn(input.regionNames, slug));
  const counts = (slug: string): Cell[] => {
    const members = regions.get(slug) ?? [];
    const funiculars = members.filter(isFunicular).length;

    return [members.length - funiculars, funiculars, members.length];
  };
  const operatorsOf = (slug: string): string =>
    [...new Set((regions.get(slug) ?? []).flatMap(line => line.operators))]
      .sort(compare)
      .join(', ');

  return [
    '## By region',
    '',
    '### Networks',
    '',
    'The regions declared in `data/regions.json`.',
    '',
    listing(
      ['Region', 'Name', 'Trains', 'Funiculars', 'Lines'],
      named.map(slug => [code(slug), input.regionNames[slug], ...counts(slug)]),
    ),
    '',
    '### Filed under their operator',
    '',
    'Funiculars, rack railways, metre-gauge operators and the German networks are',
    'each their own number space, so they are filed under the operator on purpose.',
    'An operator here that should be a network is a rule missing from',
    '`data/regions.json`.',
    '',
    listing(
      ['Region', 'Operators', 'Trains', 'Funiculars', 'Lines'],
      byOperator.map(slug => [code(slug), operatorsOf(slug), ...counts(slug)]),
    ),
  ].join('\n');
}

function unmatchedRow(
  entry: Unmatched,
  line: TerminiLine | undefined,
  reason: UnmatchedReason,
): Cell[] {
  const row: Cell[] = [
    code(entry.id),
    entry.name,
    line === undefined ? null : code(line.category),
    line?.serviceWeeks ?? null,
  ];

  if (reason === 'low-coverage') {
    return [...row, entry.best === null ? null : percent(entry.best.confidence)];
  }

  if (reason === 'contested') {
    return [...row, entry.lostTo.map(code).join(', ')];
  }

  return row;
}

function unmatchedHeaders(reason: UnmatchedReason): string[] {
  const headers = ['Line', 'Name', 'Category', 'Weeks'];

  if (reason === 'low-coverage') {
    return [...headers, 'Best coverage'];
  }

  if (reason === 'contested') {
    return [...headers, 'Lost to'];
  }

  return headers;
}

function sectionUnmatched(input: ReportInput): string {
  const lines = new Map(input.lines.map(line => [line.id, line]));
  const unmatched = byId(input.unmatched);
  const groups = REASONS.map(({ reason, says }) => {
    const entries = unmatched.filter(entry => entry.reason === reason);
    const shortLived = entries.filter(entry => isShortLived(lines.get(entry.id)));
    const lasting = entries.filter(entry => !isShortLived(lines.get(entry.id)));

    return { reason, says, entries, shortLived, lasting };
  });

  const blocks = groups.flatMap(({ reason, says, entries, shortLived, lasting }) => {
    if (entries.length === 0) {
      return [];
    }

    const rows = (subset: readonly Unmatched[]): Cell[][] =>
      subset.map(entry => unmatchedRow(entry, lines.get(entry.id), reason));
    const folded =
      shortLived.length === 0
        ? []
        : [
            '',
            '<details>',
            `<summary>${plural(shortLived.length, 'short-lived line')}, running in ${SHORT_LIVED_WEEKS} weeks or fewer</summary>`,
            '',
            table(unmatchedHeaders(reason), rows(shortLived)),
            '',
            '</details>',
          ];

    return [
      '',
      `### ${code(reason)}`,
      '',
      `${says[0].toUpperCase()}${says.slice(1)}.`,
      '',
      listing(unmatchedHeaders(reason), rows(lasting), '_Only short-lived lines._'),
      ...folded,
    ];
  });

  return [
    '## Lines with no OSM match',
    '',
    'Nothing in OpenStreetMap draws these, so `lines.geojson` has no shape for',
    `them. ${plural(unmatched.length, 'line')} in all. Weeks are the feed year’s weeks the line runs`,
    'in, and a line seeded by hand has none.',
    '',
    table(
      ['Reason', 'Lines', `Of which ${SHORT_LIVED_WEEKS} weeks or fewer`],
      groups.map(({ reason, entries, shortLived }) => [
        code(reason),
        entries.length,
        shortLived.length,
      ]),
    ),
    ...blocks,
  ].join('\n');
}

function sectionSuspects(input: ReportInput): string {
  const names = new Map(input.stations.map(station => [station.didok, station.name]));
  const stationName = (didok: string): string => names.get(didok) ?? didok;
  const blocks = byId(input.suspect).flatMap(suspect => [
    '',
    `### ${code(suspect.id)}`,
    '',
    table(
      ['Part', 'Terminals', 'Operators', 'Routes'],
      suspect.parts.map((part, index) => [
        index + 1,
        part.terminals.map(stationName).join(' – '),
        part.operators.join(', '),
        part.routeIds.length,
      ]),
    ),
  ]);

  return [
    '## Possible duplicates',
    '',
    'Each of these is one key — category, number and region — whose routes split',
    'into parts that share no station at all. They are merged so the id stays',
    'stable, but it is almost always a region rule missing from',
    '`data/regions.json`, and the fix goes there.',
    ...(blocks.length === 0 ? ['', '_None._'] : blocks),
  ].join('\n');
}

function sectionNames(input: ReportInput): string {
  const inFeed = new Set(input.inFeed);
  const derived = byId(input.lines.filter(line => line.nameSource === 'derived'));
  const flagged = derived.filter(line => line.review.length > 0);
  const plain = derived.filter(line => line.review.length === 0);
  const manual = byId(input.lines.filter(line => line.source === 'manual'));

  return [
    '## Names to check by hand',
    '',
    'A line with no public number is named from its operator, category and',
    'terminals, and a seeded line is named by whoever wrote the entry. Either is',
    'what gets corrected in Postgres after seeding; the id never moves with it.',
    '',
    '### Flagged',
    '',
    '`unknown-operator`: the operator has no short form in `data/operators.json`,',
    'so the name carries the feed’s full one. `duplicate-name`: another line came',
    'out with the same name.',
    '',
    listing(
      ['Line', 'Name', 'Flags'],
      flagged.map(line => [code(line.id), line.name, line.review.map(code).join(', ')]),
    ),
    '',
    '### Derived',
    '',
    `${plural(plain.length, 'derived name')} with no flag, each worth a glance.`,
    '',
    listing(
      ['Line', 'Name', 'Category'],
      plain.map(line => [code(line.id), line.name, code(line.category)]),
    ),
    '',
    '### Seeded by hand',
    '',
    'From `data/funiculars.json`. A seeded stop that a feed line of the same',
    'category now serves means the feed has caught up, and the entry should come',
    'out.',
    '',
    listing(
      ['Line', 'Name', 'Stops', 'Stop now in the feed'],
      manual.map(line => [
        code(line.id),
        line.name,
        line.source === 'manual' ? line.stops.length : null,
        inFeed.has(line.id) ? 'yes' : null,
      ]),
    ),
  ].join('\n');
}

function sectionFeed(input: ReportInput): string {
  const expected = '_None — the expected state._';
  const coordinate = (value: number | null): Cell => value?.toFixed(5) ?? null;
  const misplaced = [...input.misplaced].sort((a, b) => compare(a.didok, b.didok));
  const unknown = [...input.unknownRoutes].sort(
    (a, b) =>
      b.routes - a.routes ||
      compare(a.routeType, b.routeType) ||
      compare(a.routeDesc, b.routeDesc),
  );

  return [
    '## Feed checks',
    '',
    '### Stations the Swiss check doubted',
    '',
    'Swiss by their Didok number, but outside the bounding box of Switzerland or',
    'with no coordinate to check. They are kept, since the number is the stronger',
    'evidence.',
    '',
    listing(
      ['Didok', 'Name', 'Lat', 'Lon', 'Reason'],
      misplaced.map(station => [
        code(station.didok),
        station.name,
        coordinate(station.lat),
        coordinate(station.lon),
        station.reason,
      ]),
      expected,
    ),
    '',
    '### Unrecognised route types',
    '',
    'A `route_desc` in neither the include nor the exclude list, or one that has',
    'moved to another `route_type`. Its routes were dropped; decide which list it',
    'belongs on in `src/allowlist/categories.ts`.',
    '',
    listing(
      ['route_type', 'route_desc', 'Routes', 'Reason'],
      unknown.map(tally => [
        code(tally.routeType),
        tally.routeDesc === '' ? null : code(tally.routeDesc),
        tally.routes,
        tally.reason,
      ]),
      expected,
    ),
  ].join('\n');
}

export function renderReport(input: ReportInput): string {
  return `${[
    heading(input),
    sectionTotals(input.lines),
    sectionCategories(input.lines),
    sectionRegions(input),
    sectionUnmatched(input),
    sectionSuspects(input),
    sectionNames(input),
    sectionFeed(input),
  ].join('\n\n')}\n`;
}
