/**
 * Regenerates `src/lib/stats/flights/flag-data.ts` — the eleven flags inlined
 * as source, for the passport share card.
 *
 * `/stats` serves them as files, which an OG route cannot: satori resolves an
 * `<img src>` as a data URI or an absolute URL and nothing else. Reading
 * `public/flags` at render time would be the obvious answer and is the wrong
 * one — a `process.cwd()` read is invisible to Vercel's file tracing, so the
 * card would render on this machine and quietly lose its flags in production.
 *
 * Inlining moves that failure into `pnpm test`: `flag-data.test.ts` reads the
 * directory and fails if the generated copy has drifted from it. The eleven
 * come to 4,655 bytes, which is a cheaper thing to duplicate than a
 * deployment-only bug is to find.
 *
 *   pnpm og:flags
 */

import { readFileSync, readdirSync, writeFileSync } from 'node:fs';

import { registerAlias } from './lib/ts-alias.mjs';

registerAlias();

const { COUNTRIES } = await import('@/lib/stats/flights/countries');

const DIRECTORY = new URL('../public/flags/', import.meta.url);
const TARGET = new URL(
  '../src/lib/stats/flights/flag-data.ts',
  import.meta.url,
);

const files = readdirSync(DIRECTORY).filter(name => name.endsWith('.svg'));
const missing = Object.keys(COUNTRIES).filter(
  code => !files.includes(`${code}.svg`),
);

if (missing.length > 0) {
  throw new Error(`no flag file for ${missing.join(', ')}`);
}

// Keyed in the registry's order rather than the directory's, so the generated
// file reads the same way `COUNTRIES` does and a diff stays small.
const entries = Object.keys(COUNTRIES)
  .map(code => {
    const svg = readFileSync(new URL(`${code}.svg`, DIRECTORY), 'utf8').trim();

    return `  ${code}: '${svg.replace(/'/g, "\\'")}',`;
  })
  .join('\n');

const file = `/**
 * The country flags as source rather than as files, for the share card.
 *
 * Generated by \`pnpm og:flags\` from \`public/flags\`. Do not edit by hand —
 * rerun the script. The provenance and the MIT notice for the artwork itself
 * live in \`flags.ts\`, beside the function that serves the same files to
 * /stats; this module is a second reader of them, not a second source.
 *
 * Verbatim, whitespace and all, so \`flag-data.test.ts\` can compare bytes.
 */

import type { CountryCode } from '@/lib/stats/flights/countries';

const FLAG_SVG = {
${entries}
} as const satisfies Record<CountryCode, string>;

/**
 * The flag as something satori will accept as an \`<img src>\`.
 *
 * \`utf8\` rather than \`base64\`: a third shorter, no \`Buffer\`, and satori
 * decodes both. \`Object.hasOwn\` rather than \`in\` for the same reason as
 * \`country()\` — \`in\` walks the prototype chain, and \`toString\` is not a
 * country.
 */
export const flagDataUri = (code: string): string | null =>
  Object.hasOwn(FLAG_SVG, code)
    ? \`data:image/svg+xml;utf8,\${encodeURIComponent(FLAG_SVG[code as CountryCode])}\`
    : null;

export { FLAG_SVG };
`;

writeFileSync(TARGET, file);

console.log(
  `${TARGET.pathname}: ${Object.keys(COUNTRIES).length} flags inlined`,
);
