/**
 * Regenerates `src/lib/stats/flights/world-path.ts` — the land silhouette the
 * passport share card is drawn on.
 *
 * The card cannot rasterise the live globe: MapLibre needs WebGL and a tile
 * server, and an OG route has neither. So the continents are baked once, here,
 * into a single SVG path in the card's own pixel space.
 *
 * Run it when `MAP_WINDOW` or `MAP_SIZE` changes. Nothing runs it in CI —
 * `world-path.test.ts` asserts the generated window still matches the constant
 * instead, which is the same guarantee for none of the build time.
 *
 *   pnpm og:world
 */

import { writeFileSync } from 'node:fs';

import { registerAlias } from './lib/ts-alias.mjs';

registerAlias();

const { MAP_WINDOW, projectEquirectangular } =
  await import('@/lib/stats/flights/projection');

/**
 * Natural Earth 1:110m land, pinned to a tag rather than to `master` so a
 * rerun two years from now produces the same path. Public domain: "no
 * permission is needed to use Natural Earth. Crediting the authors is
 * unnecessary." Credited anyway, in the generated file.
 */
const TAG = 'v5.1.2';
const SOURCE = `https://raw.githubusercontent.com/nvkelso/natural-earth-vector/${TAG}/geojson/ne_110m_land.geojson`;

const TARGET = new URL(
  '../src/lib/stats/flights/world-path.ts',
  import.meta.url,
);

/** Rings whose projected bounding box is smaller than this are not worth a
 *  path segment at card size — they land as a speck or as nothing. */
const MIN_RING_PX = 4;

const clamp = (value, low, high) => Math.min(high, Math.max(low, value));

/** One decimal is a tenth of a pixel. Past that the string only gets longer. */
const round = value => Math.round(value * 10) / 10;

function ringToPath(ring) {
  const points = [];

  for (const [lon, lat] of ring) {
    // Clamped rather than clipped. The window spans every longitude, so the
    // only thing crossing an edge is Antarctica and the top of Greenland —
    // and a clamped vertex there just flattens against the frame, which is
    // what every banded world map does anyway.
    const [x, y] = projectEquirectangular({
      lat: clamp(lat, MAP_WINDOW.south, MAP_WINDOW.north),
      lon: clamp(lon, MAP_WINDOW.west, MAP_WINDOW.east),
    });

    const point = [round(x), round(y)];
    const previous = points.at(-1);

    // Clamping collapses runs of vertices onto the same edge pixel, and the
    // rounding collapses more. Neither is worth an `L`.
    if (previous && previous[0] === point[0] && previous[1] === point[1]) {
      continue;
    }

    points.push(point);
  }

  if (points.length < 3) return null;

  const xs = points.map(([x]) => x);
  const ys = points.map(([, y]) => y);
  const width = Math.max(...xs) - Math.min(...xs);
  const height = Math.max(...ys) - Math.min(...ys);

  if (width < MIN_RING_PX && height < MIN_RING_PX) return null;

  const [[startX, startY], ...rest] = points;

  return `M${startX} ${startY}${rest.map(([x, y]) => `L${x} ${y}`).join('')}Z`;
}

const outsideBand = ring => {
  const lats = ring.map(([, lat]) => lat);

  return (
    Math.max(...lats) < MAP_WINDOW.south || Math.min(...lats) > MAP_WINDOW.north
  );
};

const response = await fetch(SOURCE);

if (!response.ok) {
  throw new Error(`${SOURCE} answered ${response.status}`);
}

const { features } = await response.json();

const rings = features.flatMap(({ geometry }) =>
  geometry.type === 'Polygon'
    ? geometry.coordinates
    : geometry.coordinates.flat(),
);

// Antarctica is the whole of what this drops: it sits below the band, and a
// clamped version of it would paint a solid bar across the bottom edge.
const path = rings
  .filter(ring => !outsideBand(ring))
  .map(ringToPath)
  .filter(Boolean)
  .join('');

const file = `/**
 * The world's coastlines as one SVG path, in the pixel space of \`MAP_SIZE\`.
 *
 * Generated by \`pnpm og:world\` from Natural Earth 1:110m land, ${TAG}
 * (${SOURCE}). Natural Earth is in the public domain; the credit is a courtesy
 * rather than a condition. Do not edit by hand — rerun the script.
 *
 * Drawn with \`fill-rule="evenodd"\` so interior rings punch holes regardless
 * of which way round Natural Earth happened to wind them.
 */

import type { MapWindow } from '@/lib/stats/flights/projection';

/**
 * The window the path was generated against. \`world-path.test.ts\` holds it
 * equal to \`MAP_WINDOW\`, which is the only thing standing between a retuned
 * window and land that silently no longer lines up with the routes.
 */
export const WORLD_PATH_WINDOW: MapWindow = {
${Object.entries(MAP_WINDOW)
  .map(([edge, degrees]) => `  ${edge}: ${degrees},`)
  .join('\n')}
};

export const WORLD_PATH =
  '${path}';
`;

writeFileSync(TARGET, file);

console.log(
  `${TARGET.pathname}: ${rings.length} rings in, ${path.split('Z').length - 1} out, ${path.length} chars`,
);
