/**
 * `lines.csv` and `line_stops.csv` as the SQL that seeds `rail_lines` and
 * `rail_line_stops`, as a pure function from parsed rows to text.
 *
 * Generated rather than written by hand so the seed and the pipeline cannot
 * drift: the test regenerates it from the committed CSVs and compares it with
 * the committed seed byte for byte. SQL rather than `copy … from`, because
 * `supabase db reset` runs its seed files as statements and a server-side
 * `copy` cannot see a file on the laptop.
 *
 * Every insert ends `on conflict do nothing`, so running the seed twice leaves
 * the tables as the first run did — and never overwrites a row that has been
 * edited since. Replacing a snapshot that is already in the database is the
 * reconcile's job, not the seed's.
 */

import type { CsvRow } from '../diff/csv.ts';
import { LIST_SEPARATOR } from '../emit/csv.ts';
import { LINE_COLUMNS, STOP_COLUMNS } from '../emit/rows.ts';

type Kind = 'text' | 'list' | 'boolean' | 'integer' | 'number';

/**
 * How each CSV column becomes a literal. `satisfies` keeps it exhaustive; the
 * column order is `LINE_COLUMNS`'s, which is the CSV's.
 */
const LINE_KINDS = {
  id: 'text',
  display_name: 'text',
  category: 'text',
  network_region: 'text',
  operators: 'list',
  terminal_a: 'text',
  terminal_b: 'text',
  true_terminal_a: 'text',
  true_terminal_b: 'text',
  route_ids: 'list',
  seasonal: 'boolean',
  trips_per_week: 'integer',
  has_geometry: 'boolean',
} as const satisfies Record<(typeof LINE_COLUMNS)[number], Kind>;

const STOP_KINDS = {
  line_id: 'text',
  sequence: 'integer',
  stop_name: 'text',
  sloid: 'text',
  didok: 'text',
  lat: 'number',
  lon: 'number',
  via: 'text',
  junction: 'text',
} as const satisfies Record<(typeof STOP_COLUMNS)[number], Kind>;

const INTEGER = /^-?\d+$/;
const ARTICLE: Record<Kind, string> = {
  text: 'a text',
  list: 'a list',
  boolean: 'a boolean',
  integer: 'an integer',
  number: 'a number',
};
const NUMBER = /^-?\d+(\.\d+)?$/;

function text(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

/**
 * A cell as a literal, or a thrown error naming the cell. A value that does not
 * read as its column's type would otherwise surface as a Postgres error about
 * line 3,000-something of a file nobody reads.
 */
function literal(kind: Kind, value: string | null, where: string): string {
  // An empty list is written as an empty field, so it reads back as null.
  if (kind === 'list') {
    return value === null
      ? `'{}'`
      : `array[${value.split(LIST_SEPARATOR).map(text).join(', ')}]`;
  }

  if (value === null) {
    return 'null';
  }

  if (kind === 'text') {
    return text(value);
  }

  const valid =
    kind === 'boolean'
      ? value === 'true' || value === 'false'
      : (kind === 'integer' ? INTEGER : NUMBER).test(value);

  if (!valid) {
    throw new Error(
      `${where} is ${JSON.stringify(value)}, which is not ${ARTICLE[kind]}`,
    );
  }

  return value;
}

function insert(
  table: string,
  columns: readonly string[],
  kinds: Record<string, Kind>,
  conflict: string,
  rows: readonly CsvRow[],
  file: string,
): string {
  const values = rows.map((row, index) => {
    const cells = columns.map(column => {
      if (!(column in row)) {
        throw new Error(`${file} has no ${column} column`);
      }

      return literal(kinds[column], row[column], `${file} row ${index + 2} ${column}`);
    });

    return `  (${cells.join(', ')})`;
  });

  return [
    `insert into public.${table} (${columns.join(', ')}) values`,
    values.join(',\n'),
    `on conflict (${conflict}) do nothing;`,
  ].join('\n');
}

export function renderSeed(lines: readonly CsvRow[], stops: readonly CsvRow[]): string {
  const header = [
    '-- Generated by `pnpm seed:data` from rail/lines.csv and rail/line_stops.csv.',
    '-- Do not edit: rerun the command after the CSVs change. Idempotent, and it',
    '-- never overwrites a row that is already there; see rail/src/dbseed/sql.ts.',
  ].join('\n');

  // The lines first: every stop references one.
  return `${[
    header,
    insert('rail_lines', LINE_COLUMNS, LINE_KINDS, 'id', lines, 'lines.csv'),
    insert(
      'rail_line_stops',
      STOP_COLUMNS,
      STOP_KINDS,
      'line_id, sequence',
      stops,
      'line_stops.csv',
    ),
  ].join('\n\n')}\n`;
}
